name: Check Version Bump

on:
  pull_request:
    branches:
      - master
    paths:
      - 'package.json' # Opcional: solo correr si cambia este archivo o quitar para que valide siempre

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }} # Checkout de master

      - name: Get master version
        id: master_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4 # Checkout de la rama de la PR

      - name: Get PR version
        id: pr_version
        run: echo "version=$(jq -r .version package.json)" >> $GITHUB_OUTPUT

      - name: Compare Versions
        run: |
          if [ "${{ steps.master_version.outputs.version }}" == "${{ steps.pr_version.outputs.version }}" ]; then
            echo "Error: La versión en package.json no ha sido actualizada. Master está en ${{ steps.master_version.outputs.version }}."
            exit 1
          else
            echo "Perfecto: La versión ha subido de ${{ steps.master_version.outputs.version }} a ${{ steps.pr_version.outputs.version }}."
          fi